
User Guide
---------------
This part of the guide focuses on setting up your environment for X2R and all its components, including Extractor, Mapper and USS. A quickstart is then presented to give an overview of X2R and its components. Finally, details of each components are presented. 

.. toctree::
    :maxdepth: 2

    docs/install
    docs/quickstart
    docs/extractor
    docs/mapper
    docs/uss
    docs/x2r


Framework Hooks
---------------
.. toctree::
    :maxdepth: 2

    docs/hooks/new_endpoint
    docs/hooks/new_tokenizer
    docs/hooks/new_parser
    docs/hooks/new_refactor
    docs/hooks/new_selector
    docs/hooks/new_ranker
    docs/hooks/new_refiner




API Reference
-------------
This part of the documentation dedicates to prople who are looking for information on a specific function, class or method.

.. toctree::
    :maxdepth: 3

    docs/api

Additional Note
---------------
This part of note declares the license of X2R. 

.. toctree::
    :maxdepth: 2

    docs/license
